name: Deploy MERN App

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: linux-oracle
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.3.0
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'

    - name: Install the application
      run: |
        cd backend
        npm install
        pm2 restart ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production

  Release:
    runs-on: linux-oracle
    needs: [Deploy]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Zip files
      run: |
        zip -r backend.zip backend/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          backend.zip
        token: ${{ secrets.REPO_TOKEN }}
        release_name: Release ${{ github.run_number }}
        body: ${{ github.event.head_commit.message }}
        tag: ${{ github.run_number }}
        draft: false
        prerelease: false
