name: Deploy MERN App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: linux-oracle
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install the application
      run: |
        cd backend
        npm install
        npm run build
        pm2 restart ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production

 