name: Deploy MERN Backend via Podman

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Deploy Backend
    runs-on: linux-oracle

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Backend Image
      working-directory: ./backend
      run: |
        podman build -t backend-app .

    - name: Stop & Remove Old Container (if running)
      run: |
        podman stop backend || true
        podman rm backend || true

    - name: Run Backend Container
      run: |
        podman run -d \
          --name backend \
          -p 8000:8000 \
          --restart=always \
          backend-app

  release:
    name: Release backend Image
    runs-on: linux-oracle
    needs: deploy
    steps:
       
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Version Bump
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        release_branches: main

    - name: Build Release Image
      working-directory: ./backend
      run: |
        podman build -t backend-app:latest .
        ls -lah

    - name: Tag Image 
      run: |
        podman tag backend-app:latest backend-app-${{ steps.tag_version.outputs.new_tag }}

    - name: Create Release and upload image
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true
        files: |
          backend-app-${{ steps.tag_version.outputs.new_tag }}
