name: Deploy MERN Backend via Podman

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Deploy Backend
    runs-on: linux-oracle

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Backend Image
      working-directory: ./backend
      run: |
        podman build -t backend-app .

    - name: Check all pods running
      run: |
        podman ps -a

    - name: Stop & Remove Old Container (if running)
      run: |
        podman stop backend || true
        podman rm backend || true

    - name: Run Backend Container
      run: |
        podman run -d \
          --name backend \
          -p 8000:8000 \
          --restart=always \
          backend-app